### ISSUE TITLE
latest version triggers a pause on server restart via manager

### ISSUE THREAD

**Issue by stephantual** [nathannlu/ComfyUI-Pets#20]
See image below - not a big deal, but worth noting that since the last update, when you 'restart' from the 'manager interface, the server pauses specifically because of comfypets apparently.

Given that the doggo gives me a 10,000% boost in rendering times, I'd like it to work properly! 😂 

![image](https://github.com/nathannlu/ComfyUI-Pets/assets/1596070/5b297d94-df0b-4bfb-b59c-7bbc7218f4d0)

PS: everything without exception is up-to-date as of 3/25/2024 at 5:45pm.

**Comment by nathannlu** [comment]
Thanks for bringing this to my attention! Let me take a look and get back to you

**Comment by nathannlu** [comment]
hi @stephantual this should be fixed with the recent commit. Let me know if you're still running into this issue!

**Comment by stephantual** [comment]
Correct! It's now fixed 🐶 Thank you!
